import type { Metadata } from "next";
import { ReactNode, Suspense } from "react";
import NavbarComponent from "src/shared_widgets/navbar";
import LoadingSpinner from "./component/LoadingSpinner";

export const metadata: Metadata = {
  title: "DAO-Manager",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <Suspense fallback={<LoadingSpinner />}>
      <div style={{ minHeight: 100, height: "auto" }}>
        <NavbarComponent />
        <div style={{ marginTop: "85px", marginBottom: "20px" }}>
          {children}
        </div>
      </div>
    </Suspense>
  );
}
