import type { Metadata } from "next";
import { ReactNode } from "react";
import NavbarComponent from "src/shared_widgets/navbar";

export const metadata: Metadata = {
  title: "DAO-Manager",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <div style={{ minHeight: 100, height: "auto" }}>
      <NavbarComponent />
      <div style={{ marginTop: "85px", marginBottom: "20px" }}>{children}</div>
    </div>
  );
}
